services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brainagriculture
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: .
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8008 --reload
    volumes:
      - .:/app
    ports:
      - "8008:8008"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/brainagriculture
  dashboard:
    build: .
    command: uv run streamlit run app/dashboard.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - API_BASE_URL=http://api:8008
volumes:
  postgres_data: