"""init

Revision ID: 3d0a142a49a2
Revises: 
Create Date: 2025-06-23 19:02:37.665557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0a142a49a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('culturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_culturas_id'), 'culturas', ['id'], unique=False)
    op.create_table('produtores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtores_cpf_cnpj'), 'produtores', ['cpf_cnpj'], unique=True)
    op.create_index(op.f('ix_produtores_id'), 'produtores', ['id'], unique=False)
    op.create_table('safras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safras_id'), 'safras', ['id'], unique=False)
    op.create_table('propriedades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('area_total', sa.Float(), nullable=False),
    sa.Column('area_agricultavel', sa.Float(), nullable=False),
    sa.Column('area_vegetacao', sa.Float(), nullable=False),
    sa.Column('produtor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produtor_id'], ['produtores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propriedades_id'), 'propriedades', ['id'], unique=False)
    op.create_table('propriedade_safra_cultura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propriedade_id', sa.Integer(), nullable=False),
    sa.Column('safra_id', sa.Integer(), nullable=False),
    sa.Column('cultura_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cultura_id'], ['culturas.id'], ),
    sa.ForeignKeyConstraint(['propriedade_id'], ['propriedades.id'], ),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propriedade_safra_cultura_id'), 'propriedade_safra_cultura', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_propriedade_safra_cultura_id'), table_name='propriedade_safra_cultura')
    op.drop_table('propriedade_safra_cultura')
    op.drop_index(op.f('ix_propriedades_id'), table_name='propriedades')
    op.drop_table('propriedades')
    op.drop_index(op.f('ix_safras_id'), table_name='safras')
    op.drop_table('safras')
    op.drop_index(op.f('ix_produtores_id'), table_name='produtores')
    op.drop_index(op.f('ix_produtores_cpf_cnpj'), table_name='produtores')
    op.drop_table('produtores')
    op.drop_index(op.f('ix_culturas_id'), table_name='culturas')
    op.drop_table('culturas')
    # ### end Alembic commands ###
